### ISSUE TITLE
Ranking in viz

### ISSUE THREAD

**Issue by brownsarahm** [fairnessforensics/wiggum#54]
we should at least have the following ranking

- [x] immediately after compute, add distances and rank by that (default ranking) @Shine226 
- [x] option to detect threshold and rank by view count of SP occurences (as in demo) @Shine226 
- [ ] put bivariate matrices in table order including subgroup @Shine226 (moved to #62 )
- [ ] should we provide a ranking for he bivariate matrices? that is a ranking of the groupby-levels for pearson/linear and ? for rank @brownsarahm (moved to #61 )

additional steps
- [x] need to normalized the distances intno 0,1 for linear regression to make ranking with distance more intuitive @brownsarahm 

future: 
- [ ] add weighted col is untested with labeled_df (moved to #65)

Discussion: Need to decide if we want to leave the more custom ranking for current or leave it for future work with the user study.  leave for later.
